# Generated by Django 5.2 on 2026-04-29 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(max_length=20, unique=True)),
                ('nome_usuario', models.CharField(max_length=100)),
                ('categoriaUsuario', models.CharField(blank=True, max_length=50, null=True)),
                ('user_auth', models.BigIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Processamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(max_length=255, unique=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pendente'), ('PROCESSANDO', 'Processando'), ('SUCCESS', 'Sucesso'), ('ERRO', 'Erro')], default='PENDING', max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('user', models.CharField(max_length=100, null=True)),
                ('task_id_parent', models.CharField(max_length=255, null=True)),
            ],
            options={
                'unique_together': {('id', 'task_id', 'status')},
            },
        ),
        migrations.CreateModel(
            name='Acesso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_acesso', models.DateTimeField(blank=True, null=True)),
                ('desc_evento', models.CharField(max_length=100)),
                ('desc_area', models.CharField(max_length=100)),
                ('desc_leitor', models.CharField(max_length=100)),
                ('ent_sai', models.CharField(max_length=10)),
                ('apontamento', models.IntegerField(default=0)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acessos', to='smartcard.usuario', to_field='matricula')),
            ],
            options={
                'unique_together': {('usuario', 'data_acesso', 'desc_evento', 'desc_area', 'ent_sai')},
            },
        ),
    ]
