# Generated by Django 5.2 on 2026-05-21 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartcard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='processamento',
            name='task_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
