# Generated by Django 5.2 on 2026-06-23 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartcard', '0002_processamento_task_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='PushSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
