# Generated by Django 5.2 on 2026-07-02 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartcard', '0006_remove_emails_user_id_emails_esta_ativo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emails',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
