# Generated by Django 5.2 on 2026-07-08 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartcard', '0010_alter_emails_ativado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resposta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pendente'), ('PROCESSANDO', 'Processando'), ('SUCCESS', 'Sucesso'), ('ERRO', 'Erro')], default='PENDING', max_length=20)),
                ('quantidade', models.IntegerField(default=0)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
