# Generated by Django 5.2 on 2026-07-15 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartcard', '0012_alter_resposta_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resposta',
            name='quantidade',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
