# Generated by Django 5.2 on 2026-09-01 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smartcard', '0014_alter_resposta_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Resposta',
        ),
    ]
