# Generated by Django 5.2 on 2026-09-11 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartcard', '0015_delete_resposta'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='username_mrbs',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
