# Generated by Django 5.2 on 2026-09-11 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartcard', '0016_usuario_username_mrbs'),
    ]

    operations = [
        migrations.CreateModel(
            name='MrbsEntry',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('start_time', models.IntegerField()),
                ('end_time', models.IntegerField()),
                ('entry_time', models.IntegerField()),
                ('repeat_id', models.IntegerField(blank=True, null=True)),
                ('timestamp', models.IntegerField()),
                ('created_by', models.CharField(max_length=80)),
                ('modified_by', models.CharField(max_length=80)),
                ('name', models.CharField(max_length=80)),
                ('type', models.IntegerField()),
                ('description', models.TextField()),
                ('status', models.IntegerField()),
                ('reminded', models.IntegerField()),
                ('info_time', models.IntegerField()),
                ('info_user', models.CharField(max_length=80)),
                ('info_text', models.TextField()),
            ],
            options={
                'db_table': 'mrbs_entry',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CruzamentoApi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_acesso', models.DateTimeField()),
                ('porta', models.CharField(max_length=100)),
                ('motivo', models.CharField(max_length=255)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('acesso', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cruzamento', to='smartcard.acesso')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cruzamentos', to='smartcard.usuario', to_field='matricula')),
            ],
            options={
                'db_table': 'cruzamento_api',
            },
        ),
    ]
