# Generated by Django 5.2 on 2026-09-24 16:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartcard', '0017_mrbsentry_cruzamentoapi'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('USO_INDEVIDO', 'Uso Indevido do Cartão')], max_length=100)),
                ('titulo', models.CharField(max_length=200)),
                ('mensagem', models.TextField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('acesso', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificacao', to='smartcard.acesso')),
            ],
        ),
        migrations.CreateModel(
            name='NotificacaoUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lida', models.BooleanField(default=False)),
                ('lida_em', models.DateTimeField(blank=True, null=True)),
                ('notificacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarios', to='smartcard.notificacao')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes', to='smartcard.usuario', to_field='matricula')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('notificacao', 'usuario'), name='unique_notificacao_usuario')],
            },
        ),
    ]
