# Generated by Django 5.2 on 2026-09-24 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smartcard', '0018_notificacao_notificacaousuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificacao',
            name='tipo',
        ),
    ]
