# Generated by Django 5.2 on 2026-09-24 18:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartcard', '0019_remove_notificacao_tipo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificacaousuario',
            name='notificacao',
        ),
        migrations.AddField(
            model_name='notificacaousuario',
            name='acesso',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificacao', to='smartcard.acesso'),
        ),
        migrations.DeleteModel(
            name='Notificacao',
        ),
    ]
