# Generated by Django 5.2 on 2026-07-03 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartcard', '0008_emails_ativado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emails',
            name='ativado',
            field=models.BooleanField(),
        ),
    ]
