# Generated by Django 5.2 on 2026-07-15 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartcard', '0011_resposta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resposta',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pendente'), ('PROCESSANDO', 'Processando'), ('SUCCESS', 'Sucesso'), ('ERRO', 'Erro')], default='PENDING', max_length=100),
        ),
    ]
