# Generated by Django 5.2 on 2026-03-26 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smartcard', '0011_alter_processamento_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='processamento',
            unique_together={('id', 'task_id', 'status')},
        ),
    ]
