# Generated by Django 5.2 on 2026-07-15 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartcard', '0013_alter_resposta_quantidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resposta',
            name='status',
            field=models.CharField(max_length=100),
        ),
    ]
