# Generated by Django 5.2 on 2026-07-03 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartcard', '0007_alter_emails_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='emails',
            name='ativado',
            field=models.BooleanField(default=True),
        ),
    ]
