# Generated by Django 5.2 on 2026-07-03 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartcard', '0009_alter_emails_ativado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emails',
            name='ativado',
            field=models.BooleanField(default=True),
        ),
    ]
