# este docker compose é para ilustrar a estrutura do projeto, não é o docker compose final, pode conter erros e não ser otimizado para produção
# para rodar é necessário colocar esse arquivo na raiz do projeto, onde estão as pastas smartcard, users-service, frontend e docker
version: "3.9"

services:

  backend:
    build:
      context: ./smartcard
      dockerfile: docker/backend.Dockerfile

    container_name: smartcard_backend

    ports:
      - "8000:8000"

    restart: always

    volumes:
      - ./smartcard:/app
      - media_volume:/app/media

    command: >
      sh -c "
        python manage.py migrate &&
        python manage.py runserver 0.0.0.0:8000
      "

    depends_on:
      - postgres
      - redis
      - users_service

  users_service:
    build:
      context: ./users_service
      dockerfile: docker/users.Dockerfile

    container_name: users_service

    ports:
      - "8001:8001"

    restart: always

    volumes:
      - ./users_service:/app

    command: >
      sh -c "
      python manage.py migrate &&
      python manage.py runserver 0.0.0.0:8001
      "

    depends_on:
      - postgres
      - redis

  celery:
    build:
      context: ./smartcard
      dockerfile: docker/celery.Dockerfile

    container_name: smartcard_celery

    command: >
      celery -A core worker
      --loglevel=info
      --concurrency=1
      -Q fila_rapida,fila_media,fila_pesada

    restart: always

    depends_on:
      - backend
      - redis
      - users_service

    volumes:
      - ./smartcard:/app
      - media_volume:/app/media

  frontend:
    build:
      context: ./frontend

    container_name: frontend_react

    ports:
      - "3000:80"

    restart: always

    depends_on:
      - backend
      - users_service

  redis:
    image: redis:7

    container_name: redis

    ports:
      - "6379:6379"

    restart: always

  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - postgres_smartcard:/var/lib/postgresql/data   
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  media_volume:
  postgres_smartcard:
