services:

  backend:
    build:
      context: ./smartcard
      dockerfile: docker/backend.Dockerfile

    container_name: smartcard_backend

    ports:
      - "8000:8000"

    restart: always

    volumes:
      - ./smartcard:/app
      - media_volume:/app/media
      - C:/Users/anacha/Desktop/pasta:/testeshared

    environment:
      JWT_SECRET_FILE: /run/secrets/jwt_secret
      JWT_ALGORITHM_FILE: /run/secrets/jwt_algorithm
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: postgres
      DB_USER: postgres

    secrets:
      - jwt_secret
      - jwt_algorithm
      - postgres_password
      - secret_authorization
      - secret_api_key

    command: >
      sh -c "
        until python -c 'import socket; s=socket.socket(); s.connect((\"postgres\",5432))'; do
          echo 'Esperando postgres...';
          sleep 2;
        done;
        until python -c 'import socket; s=socket.socket(); s.connect((\"redis\",6379))'; do
          echo 'Esperando redis...';
          sleep 2;
        done;
        until python -c 'import socket; s=socket.socket(); s.connect((\"rabbitmq\",5672))'; do
          echo 'Esperando rabbitmq...';
          sleep 2;
        done;
        python manage.py makemigrations;
        python manage.py migrate;
        python manage.py runserver 0.0.0.0:8000 &
        celery -A core worker \
          --pool=solo \
          --concurrency=1 \
          --loglevel=info \
          -Q fila_rapida,fila_media,fila_pesada
      "

    depends_on:
      - postgres
      - redis
      - rabbitmq
      - users_service
      - mailhog

  users_service:
    build:
      context: ./users_service
      dockerfile: docker/users.Dockerfile

    container_name: users_service

    ports:
      - "8001:8000"

    restart: always

    volumes:
      - ./users_service:/app

    environment:
      JWT_SECRET: jwt_secret
      JWT_ALGORITHM: jwt_algorithm
      POSTGRES_PASSWORD: postgres_password
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: users_db
      DB_USER: postgres

    secrets:
      - jwt_secret
      - jwt_algorithm
      - postgres_password
      - secret_authorization
      - secret_api_key

    command: >
      sh -c "
        until python -c 'import socket; s=socket.socket(); s.connect((\"postgres\",5432))'; do
          echo 'Esperando postgres...';
          sleep 2;
        done;
        until python -c 'import socket; s=socket.socket(); s.connect((\"rabbitmq\",5672))'; do
          echo 'Esperando rabbitmq...';
          sleep 2;
        done;
        python manage.py makemigrations;
        python manage.py migrate;
        python manage.py init_users;
        python manage.py runserver 0.0.0.0:8000 &
        celery -A users_service worker --loglevel=info
      "

    depends_on:
      - postgres
      - redis
      - rabbitmq
      - mailhog

  frontend:
    build:
      context: ./frontend

    container_name: frontend_react

    ports:
      - "3000:80"

    restart: always

    depends_on:
      - backend
      - users_service

  redis:
    image: redis:7

    container_name: redis

    ports:
      - "6379:6379"

    restart: always

  postgres:
    image: postgres:15

    container_name: postgres

    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    ports:
      - "5432:5432"

    restart: always
    
    volumes:
      - postgres_smartcard:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  rabbitmq:
    image: rabbitmq:3-management

    container_name: rabbitmq

    ports:
      - "5672:5672"
      - "15672:15672"

    restart: always

  mailhog:
    image: mailhog/mailhog
    container_name: mailhog
    ports:
      - "8025:8025"
      - "1025:1025"
    restart: always
  
secrets:
  jwt_secret:
    file: ./secrets/jwt_secret.txt
  jwt_algorithm:
    file: ./secrets/jwt_algorithm.txt
  secret_authorization:
    file: ./secrets/secret_authorization.txt
  secret_api_key:
    file: ./secrets/secret_api_key.txt
  postgres_password:
    file: ./secrets/postgres_password.txt
    
volumes:
  media_volume:
  postgres_smartcard: