# Generated by Django 5.2 on 2026-06-24 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smartcard', '0003_pushsubscription'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PushSubscription',
        ),
    ]
