# Generated by Django 5.2 on 2026-07-02 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartcard', '0005_emails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emails',
            name='user_id',
        ),
        migrations.AddField(
            model_name='emails',
            name='esta_ativo',
            field=models.BooleanField(default=True),
        ),
    ]
